title: GermiByBike
logo: /assets/img/bikepacking-adventure-bike-vector-22446051.avif
description: Site web reprenant le suivi du voyage de Germi.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
